gin:
    mode: debug
    port: ":8080"
elastic:
    url: ""
    auth:
        username: ""
        password: ""
kafka:
    brokers:
        - ""
        - ""
        - ""
    version: ""
    group: ""
    topics:
        - ""
    assignor: ""
    oldest: true
    verbose: false
    Topic: ""

twitter:
    consumerKey: ""
    consumerSecret: ""
    accessToken: ""
    AccessTokenSecret: ""